### ISSUE TITLE
netifd: IP loss on interface after issuing "/etc/init.d/network restart"

### ISSUE THREAD

**Issue by xsokolikx** [openwrt/netifd#22]
Details
- AP with OpenWRT 23.05.02
- netifd version 2024-01-04-c18cc79d-1

Configure AP:

- Create interface _wan_ (type bridge, DHCP)
- Configure SSIDs to use _wan_ network (no encryption, default settings)
- Connect clients and launch iperf tests.

When traffic is being generated, disable the AP radios and restart network:
```
uci set wireless.radio0.disabled=1
uci set wireless.radio1.disabled=1
uci commit wireless 
/etc/init.d/network restart
```

Sometimes (it doesn't happen always), the interface _wan_ (device _br-wan_) loss it's IP, and sometimes interface _lan_ (device _br-lan_) disappears totally.

The following logs are being showed when this happens:

```
Feb  5 11:44:38 OpenWRT netifd: Network device 'wlan1' link is down
Feb  5 12:44:38 OpenWRT kernel: [ 4416.306722] br-wan: port 2(wlan1) entered disabled state
Feb  5 11:44:41 OpenWRT netifd: wan (8461): udhcpc: broadcasting renew
Feb  5 12:44:41 OpenWRT kernel: [ 4419.307703] br-wan: port 2(wlan1) entered disabled state
Feb  5 12:44:41 OpenWRT kernel: [ 4419.308207] device wlan1 left promiscuous mode
Feb  5 12:44:41 OpenWRT kernel: [ 4419.312205] br-wan: port 2(wlan1) entered disabled state
Feb  5 11:44:42 OpenWRT wpa_supplicant[2191]: Set new config for phy phy1
Feb  5 11:44:42 OpenWRT netifd: Wireless device 'radio0' is now down
Feb  5 11:44:42 OpenWRT netifd: Wireless device 'radio1' is now down
Feb  5 11:44:44 OpenWRT netifd: wan (8461): udhcpc: broadcasting renew
Feb  5 11:44:47 OpenWRT netifd: wan (8461): udhcpc: broadcasting renew
Feb  5 11:44:50 OpenWRT netifd: wan (8461): udhcpc: lease lost, entering init state
Feb  5 11:44:50 OpenWRT netifd: Interface 'wan' has lost the connection
Feb  5 12:44:50 OpenWRT dnsmasq[1]: no servers found in /tmp/resolv.conf.d/resolv.conf.auto, will retry
```

I checked that reverting https://github.com/openwrt/netifd/commit/c18cc79d50002ab8529c21184aceb016c61ac61c commit solves the issue.

Note: the problem doesn't happen if you replace _/etc/init.d/network restart_ with any of this:
- _/etc/init.d/network reload_ 
-  _ubus call network restart_ 
-  _wifi_

**Comment by xsokolikx** [comment]
> I checked that reverting [c18cc79](https://github.com/openwrt/netifd/commit/c18cc79d50002ab8529c21184aceb016c61ac61c) commit solves the issue.

After several more test, it still fails sometimes even reverting this commit.

**Comment by lynxis** [comment]
I don't understand the issue.
Can you paste the network section of your wan?
What members are part of your wan bridge? Do you have an ethernet inter in it?
On what platform are you running into this issue?

**Comment by xsokolikx** [comment]
Closing as I'm unable to reproduce the issue. Sorry for the noise
