### ISSUE TITLE
After commit a8e9085 wifi repeater not working.

### ISSUE THREAD

**Issue by McMCCRU** [openwrt/netifd#33]
After commit a8e9085 wifi repeater not working. Not found STA wifi interface, app relayd not starting. If you remove the check iface->state == IFS_UP, everything starts working...
![Screenshot_20240909_144507](https://github.com/user-attachments/assets/043a02e7-1fa1-4f9f-9081-39ee19be92cc)

**Comment by nbd168** [comment]
Fixed in 24f9a93a9559c93cf1e794fdfcd87a38d27a8e0e
